global:
  imageRegistry: docker.io
  secretKey: "mydevsecret"
  databaseUrl: "postgresql://postgres:postgres@postgres-postgresql.dev.svc.cluster.local:5432/postgres"

auth:
  image:
    repository: leogrv22/auth
    tag: dev
  secrets:
    SECRET_KEY: "mydevsecret"
    DATABASE_URL: "postgresql://postgres:postgres@postgres-postgresql.dev.svc.cluster.local:5432/postgres"

users:
  image:
    repository: leogrv22/users
    tag: dev
  secrets:
    SECRET_KEY: "mydevsecret"
    DATABASE_URL: "postgresql://postgres:postgres@postgres-postgresql.dev.svc.cluster.local:5432/postgres"

items:
  image:
    repository: leogrv22/items
    tag: dev
  secrets:
    SECRET_KEY: "mydevsecret"
    DATABASE_URL: "postgresql://postgres:postgres@postgres-postgresql.dev.svc.cluster.local:5432/postgres"
