global:
  useExternalSecrets: false
  
  database:
    host: postgres-postgresql.dev.svc.cluster.local
    port: "5432"
    name: postgres
    user: postgres
    password: postgres

auth:
  image:
    tag: dev
    pullPolicy: Always

users:
  image:
    tag: dev
    pullPolicy: Always

items:
  image:
    tag: dev
    pullPolicy: Always

frontend:
  image:
    tag: dev
    pullPolicy: Always