replicaCount: 1

image:
  registry: docker.io
  repository: titi92390/fastapi-auth
  tag: latest
  pullPolicy: IfNotPresent

env:
  APP_ENV: dev

secrets:
  SECRET_KEY: null
  DATABASE_URL: null

resources: {}

ingress:
  enabled: false
