replicaCount: 1

image:
  registry: docker.io
  repository: titi92390/fastapi-frontend
  tag: latest
  pullPolicy: IfNotPresent

env:
  APP_ENV: dev

secrets:
  SECRET_KEY: ""
  DATABASE_URL: ""

resources: {}

ingress:
  enabled: false
