controller:
  image:
    repository: jenkins/jenkins
    tag: lts-jdk17

  admin:
    username: admin
    password: admin123

  serviceType: ClusterIP
  servicePort: 8080

  persistence:
    enabled: true
    size: 10Gi

  installPlugins: []   # ⬅️ IMPORTANT : désactivation totale

  disableRememberMe: false

  jenkinsOpts:
    - "--sessionTimeout=1440"

  containerSecurityContext:
    runAsUser: 1000
    runAsGroup: 1000
    fsGroup: 1000

agent:
  enabled: true
