global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "gateway"
    metrics_path: /metrics
    static_configs:
      - targets: ["gateway:8000"]

  - job_name: "auth"
    metrics_path: /metrics
    static_configs:
      - targets: ["auth:8000"]

  - job_name: "users"
    metrics_path: /metrics
    static_configs:
      - targets: ["users:8000"]

  - job_name: "items"
    metrics_path: /metrics
    static_configs:
      - targets: ["items:8000"]
