# INGRESS pour AUTH
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gateway-auth
  namespace: dev
  annotations:
    kubernetes.io/ingress.class: traefik
    # Appliquer SEULEMENT strip-auth-prefix et rate-limit
    traefik.ingress.kubernetes.io/router.middlewares: dev-strip-auth-prefix@kubernetescrd,dev-rate-limit@kubernetescrd
spec:
  rules:
    - http:
        paths:
          - path: /auth
            pathType: Prefix
            backend:
              service:
                name: platform-auth
                port:
                  number: 80

---
# INGRESS pour USERS
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gateway-users
  namespace: dev
  annotations:
    kubernetes.io/ingress.class: traefik
    # Appliquer SEULEMENT strip-users-prefix et rate-limit
    traefik.ingress.kubernetes.io/router.middlewares: dev-strip-users-prefix@kubernetescrd,dev-rate-limit@kubernetescrd
spec:
  rules:
    - http:
        paths:
          - path: /users
            pathType: Prefix
            backend:
              service:
                name: platform-users
                port:
                  number: 80

---
# INGRESS pour ITEMS
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gateway-items
  namespace: dev
  annotations:
    kubernetes.io/ingress.class: traefik
    # Appliquer SEULEMENT strip-items-prefix et rate-limit
    traefik.ingress.kubernetes.io/router.middlewares: dev-strip-items-prefix@kubernetescrd,dev-rate-limit@kubernetescrd
spec:
  rules:
    - http:
        paths:
          - path: /items
            pathType: Prefix
            backend:
              service:
                name: platform-items
                port:
                  number: 80