apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: api-chain
  namespace: fastapi
spec:
  chain:
    middlewares:
      - name: strip-auth
      - name: strip-users
      - name: strip-items
