apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: platform-gateway
  namespace: fastapi
  annotations:
    # Entrypoint HTTPS uniquement
    traefik.ingress.kubernetes.io/router.entrypoints: websecure

    # Middlewares Traefik (strip / sécurité)
    traefik.ingress.kubernetes.io/router.middlewares: |
      fastapi-strip-auth@kubernetescrd,
      fastapi-strip-users@kubernetescrd,
      fastapi-strip-items@kubernetescrd

spec:
  # IngressClass moderne (remplace l’annotation legacy)
  ingressClassName: traefik

  # TLS (Let’s Encrypt / cert-manager / Traefik ACME)
  tls:
    - hosts:
        - fastapi-tiffanie.duckdns.org
      secretName: fastapi-tls

  rules:
    - host: fastapi-tiffanie.duckdns.org
      http:
        paths:
          - path: /api/auth
            pathType: Prefix
            backend:
              service:
                name: platform-auth
                port:
                  number: 80

          - path: /api/users
            pathType: Prefix
            backend:
              service:
                name: platform-users
                port:
                  number: 80

          - path: /api/items
            pathType: Prefix
            backend:
              service:
                name: platform-items
                port:
                  number: 80
