apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: fastapi-api
  namespace: fastapi
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.ingress.kubernetes.io/router.entrypoints: web
spec:
  rules:
    - http:
        paths:
          - path: /auth
            pathType: Prefix
            backend:
              service:
                name: platform-auth
                port:
                  number: 80

          - path: /users
            pathType: Prefix
            backend:
              service:
                name: platform-users
                port:
                  number: 80

          - path: /items
            pathType: Prefix
            backend:
              service:
                name: platform-items
                port:
                  number: 80
