apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "items.fullname" . }}
  labels:
    {{ include "items.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "items.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "items.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:

      {{- if eq .Values.global.waitForDatabase true }}
      initContainers:
        - name: wait-for-db
          image: busybox:1.36
          command: ['sh', '-c']
          args:
            - |
              until nslookup postgres.{{ .Release.Namespace }}.svc.cluster.local; do
                sleep 3;
              done
      {{- end }}

      containers:
        - name: items
          image: "{{ .Values.global.imageRegistry }}/{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8000
              name: http
