apiVersion: v1
kind: Secret
metadata:
  name: {{ include "items.fullname" . }}-secret
type: Opaque
stringData:
  SECRET_KEY: {{ .Values.secrets.SECRET_KEY | default .Values.global.secretKey | quote }}
  DATABASE_URL: {{ .Values.secrets.DATABASE_URL | default .Values.global.databaseUrl | quote }}
