apiVersion: v1
kind: Secret
metadata:
  name: {{ include "auth.fullname" . }}-secret
type: Opaque
stringData:
  SECRET_KEY: {{ coalesce .Values.secrets.SECRET_KEY .Values.global.secretKey | quote }}
  DATABASE_URL: {{ coalesce .Values.secrets.DATABASE_URL .Values.global.databaseUrl | quote }}

