apiVersion: v2
name: platform
description: Umbrella chart to deploy microservices
type: application
version: 0.1.0
appVersion: "0.1.0"
dependencies:
  - name: auth
    version: 0.1.0
    repository: "file://../auth"
  - name: users
    version: 0.1.0
    repository: "file://../users"
  - name: items
    version: 0.1.0
    repository: "file://../items"
  - name: frontend
    version: 0.1.0
    repository: "file://../frontend"