############################
# GLOBAL
############################
global:
  environment: prod
  domain: platform.apisep25.fr
  image:
    registry: docker.io
  database:
    host: postgres.fastapi.svc.cluster.local
    port: 5432
    name: app_db
    user: postgres
    secretName: database-credentials

############################
# AUTH SERVICE
############################
auth:
  enabled: true
  replicaCount: 1

  image:
    repository: titi92390/fastapi-auth
    tag: latest
    pullPolicy: IfNotPresent

  resources:
    requests:
      cpu: 250m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi

  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 3
    targetCPUUtilizationPercentage: 70

  service:
    type: ClusterIP
    port: 80

############################
# USERS SERVICE
############################
users:
  enabled: true
  replicaCount: 1

  image:
    repository: titi92390/fastapi-users
    tag: latest
    pullPolicy: IfNotPresent

  resources:
    requests:
      cpu: 250m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi

  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 3
    targetCPUUtilizationPercentage: 70

  service:
    type: ClusterIP
    port: 80

############################
# ITEMS SERVICE
############################
items:
  enabled: true
  replicaCount: 1

  image:
    repository: titi92390/fastapi-items
    tag: latest
    pullPolicy: IfNotPresent

  resources:
    requests:
      cpu: 250m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi

  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 3
    targetCPUUtilizationPercentage: 70

  service:
    type: ClusterIP
    port: 80

############################
# FRONTEND
############################
frontend:
  enabled: false
  replicaCount: 0

  image:
    repository: titi92390/frontend
    tag: latest
    pullPolicy: IfNotPresent

  resources:
    requests:
      cpu: 250m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi

  autoscaling:
    enabled: false
    minReplicas: 0
    maxReplicas: 3
    targetCPUUtilizationPercentage: 70

  service:
    type: ClusterIP
    port: 80

############################
# INGRESS (ALB)
############################
ingress:
  enabled: true
  className: alb
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP":80},{"HTTPS":443}]'
    alb.ingress.kubernetes.io/ssl-redirect: "443"
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:eu-west-3:131674823919:certificate/eca8c675-f1f8-431f-a8b2-686c65c56915
    alb.ingress.kubernetes.io/healthcheck-path: /health
    alb.ingress.kubernetes.io/healthcheck-interval-seconds: "30"
    alb.ingress.kubernetes.io/healthy-threshold-count: "2"
    alb.ingress.kubernetes.io/unhealthy-threshold-count: "3"

  hosts:
    - host: platform.apisep25.fr
      paths:
        - path: /api/auth
          pathType: Prefix
          backend:
            service:
              name: platform-auth
              port:
                number: 80

        - path: /api/users
          pathType: Prefix
          backend:
            service:
              name: platform-users
              port:
                number: 80

        - path: /api/items
          pathType: Prefix
          backend:
            service:
              name: platform-items
              port:
                number: 80

        - path: /
          pathType: Prefix
          backend:
            service:
              name: platform-frontend
              port:
                number: 80

############################
# POD DISRUPTION BUDGET
############################
podDisruptionBudget:
  enabled: false
  minAvailable: 1
