imagePullSecrets:
  - name: dockerhub

auth:
  replicaCount: 1
  image:
    repository: titi92390/fastapi-auth
    tag: latest
    pullPolicy: Always

users:
  replicaCount: 1
  image:
    repository: titi92390/fastapi-users
    tag: latest
    pullPolicy: Always

items:
  replicaCount: 1
  image:
    repository: titi92390/fastapi-items
    tag: latest
    pullPolicy: Always

gateway:
  replicaCount: 1
  image:
    repository: titi92390/fastapi-gateway
    tag: latest
    pullPolicy: Always

frontend:
  replicaCount: 1
  image:
    repository: titi92390/fastapi-frontend
    tag: latest
    pullPolicy: Always


auth:
  secrets:
    SECRET_KEY: "dev-secret-key-auth"

users:
  secrets:
    SECRET_KEY: "dev-secret-key-users"

items:
  secrets:
    SECRET_KEY: "dev-secret-key-items"
